import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./footer/Footer";
import Nabvar from "@/components/nabvar/Navbar";
import Nav from "@/components/nabvar/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nabvar></Nabvar>
        <Nav></Nav>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
